actor_hidden_size: 64
batch_size: 256
clip_eps: 0.2
critic_hidden_size: 64
discount: 0.99
dissim_coef: 0.0
entropy_coef: 0.0005
entropy_decay: 0
env_args:
  render_mode: rgb_array
epochs: 4
feature_hidden_size: 128
feature_learn: cm
feature_learn_hidden_size: 64
feature_size: 64
frames: 10000000
frames_per_proc: null
gae_lambda: 0.95
input: auto
load_optimizer_state: false
log_interval: 1
lr: 0.001
lr_a: 0.001
lr_f: 0.001
lr_r: 0.0001
lr_sr: 0.001
max_grad_norm: 10
memory_cap: 100000
model: null
n_test_episodes: 10
normlize_embeddings: false
optim_alpha: 0.99
optim_eps: 1.0e-08
plot: false
procs: 5
recurrence: 1
save_interval: 10
seed: 1
ssp_dim: 151
ssp_h: 1.0
text: false
value_loss_coef: 0.5
verbose: true
wrapper: none
normalize_embeddings: False
wandb: False
wandb_project_name: sfa2c
wandb_entity: null
wandb_tags: []

